version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    expose:
      - "11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    networks:
      - ollama_internal
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/tags"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 15s

  websocket-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ollama-ws-server
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - OLLAMA_API_URL=http://ollama:11434
      - PORT=3000
      - HOST=0.0.0.0
      - LOG_LEVEL=info
    restart: unless-stopped
    depends_on:
      ollama:
        condition: service_healthy
    networks:
      - ollama_internal

volumes:
  ollama_data:
    name: ollama_data

networks:
  ollama_internal:
    driver: bridge
